<?php

namespace App\GaelO\Constants;

class MailConstants {

    const EMAIL_REQUEST = 0;
    const EMAIL_VISIT_NOT_DONE=1;
    const EMAIL_UPLOAD_FAILURE=3;
    const EMAIL_UPLOADED_VISIT=4;
    const EMAIL_UNLOCK_REQUEST=5;
    const EMAIL_UNLOCK_FORM=6;
    const EMAIL_REVIEW_READY=8;
    const EMAIL_QC_DECISION=10;
    const EMAIL_DELETED_FORM=11;
    const EMAIL_CORRECTIVE_ACTION=12;
    const EMAIL_CONCLUSION=13;
    const EMAIL_CHANGE_PASSWORD_DEACTIVATED=14;
    const EMAIL_BLOCKED_ACCOUNT=15;
    const EMAIL_ADMIN_LOGGED=16;
    const EMAIL_ADJUDICATION=17;
    const EMAIL_IMPORT_PATIENT=18;
    const EMAIL_REMINDER=19;
    const EMAIL_USER=20;
}
