<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contryArray = array(
            array('code' => 'AC','country_us' => 'Ascension Island','country_fr' => 'Île de l’Ascension'),
            array('code' => 'AD','country_us' => 'Andorra','country_fr' => 'Andorre'),
            array('code' => 'AE','country_us' => 'United Arab Emirates','country_fr' => 'Émirats arabes unis'),
            array('code' => 'AF','country_us' => 'Afghanistan','country_fr' => 'Afghanistan'),
            array('code' => 'AG','country_us' => 'Antigua & Barbuda','country_fr' => 'Antigua-et-Barbuda'),
            array('code' => 'AI','country_us' => 'Anguilla','country_fr' => 'Anguilla'),
            array('code' => 'AL','country_us' => 'Albania','country_fr' => 'Albanie'),
            array('code' => 'AM','country_us' => 'Armenia','country_fr' => 'Arménie'),
            array('code' => 'AO','country_us' => 'Angola','country_fr' => 'Angola'),
            array('code' => 'AQ','country_us' => 'Antarctica','country_fr' => 'Antarctique'),
            array('code' => 'AR','country_us' => 'Argentina','country_fr' => 'Argentine'),
            array('code' => 'AS','country_us' => 'American Samoa','country_fr' => 'Samoa américaines'),
            array('code' => 'AT','country_us' => 'Austria','country_fr' => 'Autriche'),
            array('code' => 'AU','country_us' => 'Australia','country_fr' => 'Australie'),
            array('code' => 'AW','country_us' => 'Aruba','country_fr' => 'Aruba'),
            array('code' => 'AX','country_us' => 'Åland Islands','country_fr' => 'Îles Åland'),
            array('code' => 'AZ','country_us' => 'Azerbaijan','country_fr' => 'Azerbaïdjan'),
            array('code' => 'BA','country_us' => 'Bosnia & Herzegovina','country_fr' => 'Bosnie-Herzégovine'),
            array('code' => 'BB','country_us' => 'Barbados','country_fr' => 'Barbade'),
            array('code' => 'BD','country_us' => 'Bangladesh','country_fr' => 'Bangladesh'),
            array('code' => 'BE','country_us' => 'Belgium','country_fr' => 'Belgique'),
            array('code' => 'BF','country_us' => 'Burkina Faso','country_fr' => 'Burkina Faso'),
            array('code' => 'BG','country_us' => 'Bulgaria','country_fr' => 'Bulgarie'),
            array('code' => 'BH','country_us' => 'Bahrain','country_fr' => 'Bahreïn'),
            array('code' => 'BI','country_us' => 'Burundi','country_fr' => 'Burundi'),
            array('code' => 'BJ','country_us' => 'Benin','country_fr' => 'Bénin'),
            array('code' => 'BL','country_us' => 'St. Barthélemy','country_fr' => 'Saint-Barthélemy'),
            array('code' => 'BM','country_us' => 'Bermuda','country_fr' => 'Bermudes'),
            array('code' => 'BN','country_us' => 'Brunei','country_fr' => 'Brunéi Darussalam'),
            array('code' => 'BO','country_us' => 'Bolivia','country_fr' => 'Bolivie'),
            array('code' => 'BQ','country_us' => 'Caribbean Netherlands','country_fr' => 'Pays-Bas caribéens'),
            array('code' => 'BR','country_us' => 'Brazil','country_fr' => 'Brésil'),
            array('code' => 'BS','country_us' => 'Bahamas','country_fr' => 'Bahamas'),
            array('code' => 'BT','country_us' => 'Bhutan','country_fr' => 'Bhoutan'),
            array('code' => 'BW','country_us' => 'Botswana','country_fr' => 'Botswana'),
            array('code' => 'BY','country_us' => 'Belarus','country_fr' => 'Biélorussie'),
            array('code' => 'BZ','country_us' => 'Belize','country_fr' => 'Belize'),
            array('code' => 'CA','country_us' => 'Canada','country_fr' => 'Canada'),
            array('code' => 'CC','country_us' => 'Cocos (Keeling) Islands','country_fr' => 'Îles Cocos'),
            array('code' => 'CD','country_us' => 'Congo - Kinshasa','country_fr' => 'Congo-Kinshasa'),
            array('code' => 'CF','country_us' => 'Central African Republic','country_fr' => 'République centrafricaine'),
            array('code' => 'CG','country_us' => 'Congo - Brazzaville','country_fr' => 'Congo-Brazzaville'),
            array('code' => 'CH','country_us' => 'Switzerland','country_fr' => 'Suisse'),
            array('code' => 'CI','country_us' => 'Côte d’Ivoire','country_fr' => 'Côte d’Ivoire'),
            array('code' => 'CK','country_us' => 'Cook Islands','country_fr' => 'Îles Cook'),
            array('code' => 'CL','country_us' => 'Chile','country_fr' => 'Chili'),
            array('code' => 'CM','country_us' => 'Cameroon','country_fr' => 'Cameroun'),
            array('code' => 'CN','country_us' => 'China','country_fr' => 'Chine'),
            array('code' => 'CO','country_us' => 'Colombia','country_fr' => 'Colombie'),
            array('code' => 'CR','country_us' => 'Costa Rica','country_fr' => 'Costa Rica'),
            array('code' => 'CU','country_us' => 'Cuba','country_fr' => 'Cuba'),
            array('code' => 'CV','country_us' => 'Cape Verde','country_fr' => 'Cap-Vert'),
            array('code' => 'CW','country_us' => 'Curaçao','country_fr' => 'Curaçao'),
            array('code' => 'CX','country_us' => 'Christmas Island','country_fr' => 'Île Christmas'),
            array('code' => 'CY','country_us' => 'Cyprus','country_fr' => 'Chypre'),
            array('code' => 'CZ','country_us' => 'Czechia','country_fr' => 'Tchéquie'),
            array('code' => 'DE','country_us' => 'Germany','country_fr' => 'Allemagne'),
            array('code' => 'DG','country_us' => 'Diego Garcia','country_fr' => 'Diego Garcia'),
            array('code' => 'DJ','country_us' => 'Djibouti','country_fr' => 'Djibouti'),
            array('code' => 'DK','country_us' => 'Denmark','country_fr' => 'Danemark'),
            array('code' => 'DM','country_us' => 'Dominica','country_fr' => 'Dominique'),
            array('code' => 'DO','country_us' => 'Dominican Republic','country_fr' => 'République dominicaine'),
            array('code' => 'DZ','country_us' => 'Algeria','country_fr' => 'Algérie'),
            array('code' => 'EA','country_us' => 'Ceuta & Melilla','country_fr' => 'Ceuta et Melilla'),
            array('code' => 'EC','country_us' => 'Ecuador','country_fr' => 'Équateur'),
            array('code' => 'EE','country_us' => 'Estonia','country_fr' => 'Estonie'),
            array('code' => 'EG','country_us' => 'Egypt','country_fr' => 'Égypte'),
            array('code' => 'EH','country_us' => 'Western Sahara','country_fr' => 'Sahara occidental'),
            array('code' => 'ER','country_us' => 'Eritrea','country_fr' => 'Érythrée'),
            array('code' => 'ES','country_us' => 'Spain','country_fr' => 'Espagne'),
            array('code' => 'ET','country_us' => 'Ethiopia','country_fr' => 'Éthiopie'),
            array('code' => 'FI','country_us' => 'Finland','country_fr' => 'Finlande'),
            array('code' => 'FJ','country_us' => 'Fiji','country_fr' => 'Fidji'),
            array('code' => 'FK','country_us' => 'Falkland Islands','country_fr' => 'Îles Malouines'),
            array('code' => 'FM','country_us' => 'Micronesia','country_fr' => 'États fédérés de Micronésie'),
            array('code' => 'FO','country_us' => 'Faroe Islands','country_fr' => 'Îles Féroé'),
            array('code' => 'FR','country_us' => 'France','country_fr' => 'France'),
            array('code' => 'GA','country_us' => 'Gabon','country_fr' => 'Gabon'),
            array('code' => 'GB','country_us' => 'United Kingdom','country_fr' => 'Royaume-Uni'),
            array('code' => 'GD','country_us' => 'Grenada','country_fr' => 'Grenade'),
            array('code' => 'GE','country_us' => 'Georgia','country_fr' => 'Géorgie'),
            array('code' => 'GF','country_us' => 'French Guiana','country_fr' => 'Guyane française'),
            array('code' => 'GG','country_us' => 'Guernsey','country_fr' => 'Guernesey'),
            array('code' => 'GH','country_us' => 'Ghana','country_fr' => 'Ghana'),
            array('code' => 'GI','country_us' => 'Gibraltar','country_fr' => 'Gibraltar'),
            array('code' => 'GL','country_us' => 'Greenland','country_fr' => 'Groenland'),
            array('code' => 'GM','country_us' => 'Gambia','country_fr' => 'Gambie'),
            array('code' => 'GN','country_us' => 'Guinea','country_fr' => 'Guinée'),
            array('code' => 'GP','country_us' => 'Guadeloupe','country_fr' => 'Guadeloupe'),
            array('code' => 'GQ','country_us' => 'Equatorial Guinea','country_fr' => 'Guinée équatoriale'),
            array('code' => 'GR','country_us' => 'Greece','country_fr' => 'Grèce'),
            array('code' => 'GS','country_us' => 'South Georgia & South Sandwich Islands','country_fr' => 'Géorgie du Sud et îles Sandwich du Sud'),
            array('code' => 'GT','country_us' => 'Guatemala','country_fr' => 'Guatemala'),
            array('code' => 'GU','country_us' => 'Guam','country_fr' => 'Guam'),
            array('code' => 'GW','country_us' => 'Guinea-Bissau','country_fr' => 'Guinée-Bissau'),
            array('code' => 'GY','country_us' => 'Guyana','country_fr' => 'Guyana'),
            array('code' => 'HK','country_us' => 'Hong Kong SAR China','country_fr' => 'R.A.S. chinoise de Hong Kong'),
            array('code' => 'HN','country_us' => 'Honduras','country_fr' => 'Honduras'),
            array('code' => 'HR','country_us' => 'Croatia','country_fr' => 'Croatie'),
            array('code' => 'HT','country_us' => 'Haiti','country_fr' => 'Haïti'),
            array('code' => 'HU','country_us' => 'Hungary','country_fr' => 'Hongrie'),
            array('code' => 'IC','country_us' => 'Canary Islands','country_fr' => 'Îles Canaries'),
            array('code' => 'ID','country_us' => 'Indonesia','country_fr' => 'Indonésie'),
            array('code' => 'IE','country_us' => 'Ireland','country_fr' => 'Irlande'),
            array('code' => 'IL','country_us' => 'Israel','country_fr' => 'Israël'),
            array('code' => 'IM','country_us' => 'Isle of Man','country_fr' => 'Île de Man'),
            array('code' => 'IN','country_us' => 'India','country_fr' => 'Inde'),
            array('code' => 'IO','country_us' => 'British Indian Ocean Territory','country_fr' => 'Territoire britannique de l’océan Indien'),
            array('code' => 'IQ','country_us' => 'Iraq','country_fr' => 'Irak'),
            array('code' => 'IR','country_us' => 'Iran','country_fr' => 'Iran'),
            array('code' => 'IS','country_us' => 'Iceland','country_fr' => 'Islande'),
            array('code' => 'IT','country_us' => 'Italy','country_fr' => 'Italie'),
            array('code' => 'JE','country_us' => 'Jersey','country_fr' => 'Jersey'),
            array('code' => 'JM','country_us' => 'Jamaica','country_fr' => 'Jamaïque'),
            array('code' => 'JO','country_us' => 'Jordan','country_fr' => 'Jordanie'),
            array('code' => 'JP','country_us' => 'Japan','country_fr' => 'Japon'),
            array('code' => 'KE','country_us' => 'Kenya','country_fr' => 'Kenya'),
            array('code' => 'KG','country_us' => 'Kyrgyzstan','country_fr' => 'Kirghizistan'),
            array('code' => 'KH','country_us' => 'Cambodia','country_fr' => 'Cambodge'),
            array('code' => 'KI','country_us' => 'Kiribati','country_fr' => 'Kiribati'),
            array('code' => 'KM','country_us' => 'Comoros','country_fr' => 'Comores'),
            array('code' => 'KN','country_us' => 'St. Kitts & Nevis','country_fr' => 'Saint-Christophe-et-Niévès'),
            array('code' => 'KP','country_us' => 'North Korea','country_fr' => 'Corée du Nord'),
            array('code' => 'KR','country_us' => 'South Korea','country_fr' => 'Corée du Sud'),
            array('code' => 'KW','country_us' => 'Kuwait','country_fr' => 'Koweït'),
            array('code' => 'KY','country_us' => 'Cayman Islands','country_fr' => 'Îles Caïmans'),
            array('code' => 'KZ','country_us' => 'Kazakhstan','country_fr' => 'Kazakhstan'),
            array('code' => 'LA','country_us' => 'Laos','country_fr' => 'Laos'),
            array('code' => 'LB','country_us' => 'Lebanon','country_fr' => 'Liban'),
            array('code' => 'LC','country_us' => 'St. Lucia','country_fr' => 'Sainte-Lucie'),
            array('code' => 'LI','country_us' => 'Liechtenstein','country_fr' => 'Liechtenstein'),
            array('code' => 'LK','country_us' => 'Sri Lanka','country_fr' => 'Sri Lanka'),
            array('code' => 'LR','country_us' => 'Liberia','country_fr' => 'Libéria'),
            array('code' => 'LS','country_us' => 'Lesotho','country_fr' => 'Lesotho'),
            array('code' => 'LT','country_us' => 'Lithuania','country_fr' => 'Lituanie'),
            array('code' => 'LU','country_us' => 'Luxembourg','country_fr' => 'Luxembourg'),
            array('code' => 'LV','country_us' => 'Latvia','country_fr' => 'Lettonie'),
            array('code' => 'LY','country_us' => 'Libya','country_fr' => 'Libye'),
            array('code' => 'MA','country_us' => 'Morocco','country_fr' => 'Maroc'),
            array('code' => 'MC','country_us' => 'Monaco','country_fr' => 'Monaco'),
            array('code' => 'MD','country_us' => 'Moldova','country_fr' => 'Moldavie'),
            array('code' => 'ME','country_us' => 'Montenegro','country_fr' => 'Monténégro'),
            array('code' => 'MF','country_us' => 'St. Martin','country_fr' => 'Saint-Martin'),
            array('code' => 'MG','country_us' => 'Madagascar','country_fr' => 'Madagascar'),
            array('code' => 'MH','country_us' => 'Marshall Islands','country_fr' => 'Îles Marshall'),
            array('code' => 'MK','country_us' => 'North Macedonia','country_fr' => 'Macédoine'),
            array('code' => 'ML','country_us' => 'Mali','country_fr' => 'Mali'),
            array('code' => 'MM','country_us' => 'Myanmar (Burma)','country_fr' => 'Myanmar (Birmanie)'),
            array('code' => 'MN','country_us' => 'Mongolia','country_fr' => 'Mongolie'),
            array('code' => 'MO','country_us' => 'Macao SAR China','country_fr' => 'R.A.S. chinoise de Macao'),
            array('code' => 'MP','country_us' => 'Northern Mariana Islands','country_fr' => 'Îles Mariannes du Nord'),
            array('code' => 'MQ','country_us' => 'Martinique','country_fr' => 'Martinique'),
            array('code' => 'MR','country_us' => 'Mauritania','country_fr' => 'Mauritanie'),
            array('code' => 'MS','country_us' => 'Montserrat','country_fr' => 'Montserrat'),
            array('code' => 'MT','country_us' => 'Malta','country_fr' => 'Malte'),
            array('code' => 'MU','country_us' => 'Mauritius','country_fr' => 'Maurice'),
            array('code' => 'MV','country_us' => 'Maldives','country_fr' => 'Maldives'),
            array('code' => 'MW','country_us' => 'Malawi','country_fr' => 'Malawi'),
            array('code' => 'MX','country_us' => 'Mexico','country_fr' => 'Mexique'),
            array('code' => 'MY','country_us' => 'Malaysia','country_fr' => 'Malaisie'),
            array('code' => 'MZ','country_us' => 'Mozambique','country_fr' => 'Mozambique'),
            array('code' => 'NA','country_us' => 'Namibia','country_fr' => 'Namibie'),
            array('code' => 'NC','country_us' => 'New Caledonia','country_fr' => 'Nouvelle-Calédonie'),
            array('code' => 'NE','country_us' => 'Niger','country_fr' => 'Niger'),
            array('code' => 'NF','country_us' => 'Norfolk Island','country_fr' => 'Île Norfolk'),
            array('code' => 'NG','country_us' => 'Nigeria','country_fr' => 'Nigéria'),
            array('code' => 'NI','country_us' => 'Nicaragua','country_fr' => 'Nicaragua'),
            array('code' => 'NL','country_us' => 'Netherlands','country_fr' => 'Pays-Bas'),
            array('code' => 'NO','country_us' => 'Norway','country_fr' => 'Norvège'),
            array('code' => 'NP','country_us' => 'Nepal','country_fr' => 'Népal'),
            array('code' => 'NR','country_us' => 'Nauru','country_fr' => 'Nauru'),
            array('code' => 'NU','country_us' => 'Niue','country_fr' => 'Niue'),
            array('code' => 'NZ','country_us' => 'New Zealand','country_fr' => 'Nouvelle-Zélande'),
            array('code' => 'OM','country_us' => 'Oman','country_fr' => 'Oman'),
            array('code' => 'PA','country_us' => 'Panama','country_fr' => 'Panama'),
            array('code' => 'PE','country_us' => 'Peru','country_fr' => 'Pérou'),
            array('code' => 'PF','country_us' => 'French Polynesia','country_fr' => 'Polynésie française'),
            array('code' => 'PG','country_us' => 'Papua New Guinea','country_fr' => 'Papouasie-Nouvelle-Guinée'),
            array('code' => 'PH','country_us' => 'Philippines','country_fr' => 'Philippines'),
            array('code' => 'PK','country_us' => 'Pakistan','country_fr' => 'Pakistan'),
            array('code' => 'PL','country_us' => 'Poland','country_fr' => 'Pologne'),
            array('code' => 'PM','country_us' => 'St. Pierre & Miquelon','country_fr' => 'Saint-Pierre-et-Miquelon'),
            array('code' => 'PN','country_us' => 'Pitcairn Islands','country_fr' => 'Îles Pitcairn'),
            array('code' => 'PR','country_us' => 'Puerto Rico','country_fr' => 'Porto Rico'),
            array('code' => 'PS','country_us' => 'Palestinian Territories','country_fr' => 'Territoires palestiniens'),
            array('code' => 'PT','country_us' => 'Portugal','country_fr' => 'Portugal'),
            array('code' => 'PW','country_us' => 'Palau','country_fr' => 'Palaos'),
            array('code' => 'PY','country_us' => 'Paraguay','country_fr' => 'Paraguay'),
            array('code' => 'QA','country_us' => 'Qatar','country_fr' => 'Qatar'),
            array('code' => 'RE','country_us' => 'Réunion','country_fr' => 'La Réunion'),
            array('code' => 'RO','country_us' => 'Romania','country_fr' => 'Roumanie'),
            array('code' => 'RS','country_us' => 'Serbia','country_fr' => 'Serbie'),
            array('code' => 'RU','country_us' => 'Russia','country_fr' => 'Russie'),
            array('code' => 'RW','country_us' => 'Rwanda','country_fr' => 'Rwanda'),
            array('code' => 'SA','country_us' => 'Saudi Arabia','country_fr' => 'Arabie saoudite'),
            array('code' => 'SB','country_us' => 'Solomon Islands','country_fr' => 'Îles Salomon'),
            array('code' => 'SC','country_us' => 'Seychelles','country_fr' => 'Seychelles'),
            array('code' => 'SD','country_us' => 'Sudan','country_fr' => 'Soudan'),
            array('code' => 'SE','country_us' => 'Sweden','country_fr' => 'Suède'),
            array('code' => 'SG','country_us' => 'Singapore','country_fr' => 'Singapour'),
            array('code' => 'SH','country_us' => 'St. Helena','country_fr' => 'Sainte-Hélène'),
            array('code' => 'SI','country_us' => 'Slovenia','country_fr' => 'Slovénie'),
            array('code' => 'SJ','country_us' => 'Svalbard & Jan Mayen','country_fr' => 'Svalbard et Jan Mayen'),
            array('code' => 'SK','country_us' => 'Slovakia','country_fr' => 'Slovaquie'),
            array('code' => 'SL','country_us' => 'Sierra Leone','country_fr' => 'Sierra Leone'),
            array('code' => 'SM','country_us' => 'San Marino','country_fr' => 'Saint-Marin'),
            array('code' => 'SN','country_us' => 'Senegal','country_fr' => 'Sénégal'),
            array('code' => 'SO','country_us' => 'Somalia','country_fr' => 'Somalie'),
            array('code' => 'SR','country_us' => 'Suriname','country_fr' => 'Suriname'),
            array('code' => 'SS','country_us' => 'South Sudan','country_fr' => 'Soudan du Sud'),
            array('code' => 'ST','country_us' => 'São Tomé & Príncipe','country_fr' => 'Sao Tomé-et-Principe'),
            array('code' => 'SV','country_us' => 'El Salvador','country_fr' => 'Salvador'),
            array('code' => 'SX','country_us' => 'Sint Maarten','country_fr' => 'Saint-Martin (partie néerlandaise)'),
            array('code' => 'SY','country_us' => 'Syria','country_fr' => 'Syrie'),
            array('code' => 'SZ','country_us' => 'Eswatini','country_fr' => 'Eswatini'),
            array('code' => 'TA','country_us' => 'Tristan da Cunha','country_fr' => 'Tristan da Cunha'),
            array('code' => 'TC','country_us' => 'Turks & Caicos Islands','country_fr' => 'Îles Turques-et-Caïques'),
            array('code' => 'TD','country_us' => 'Chad','country_fr' => 'Tchad'),
            array('code' => 'TF','country_us' => 'French Southern Territories','country_fr' => 'Terres australes françaises'),
            array('code' => 'TG','country_us' => 'Togo','country_fr' => 'Togo'),
            array('code' => 'TH','country_us' => 'Thailand','country_fr' => 'Thaïlande'),
            array('code' => 'TJ','country_us' => 'Tajikistan','country_fr' => 'Tadjikistan'),
            array('code' => 'TK','country_us' => 'Tokelau','country_fr' => 'Tokelau'),
            array('code' => 'TL','country_us' => 'Timor-Leste','country_fr' => 'Timor oriental'),
            array('code' => 'TM','country_us' => 'Turkmenistan','country_fr' => 'Turkménistan'),
            array('code' => 'TN','country_us' => 'Tunisia','country_fr' => 'Tunisie'),
            array('code' => 'TO','country_us' => 'Tonga','country_fr' => 'Tonga'),
            array('code' => 'TR','country_us' => 'Turkey','country_fr' => 'Turquie'),
            array('code' => 'TT','country_us' => 'Trinidad & Tobago','country_fr' => 'Trinité-et-Tobago'),
            array('code' => 'TV','country_us' => 'Tuvalu','country_fr' => 'Tuvalu'),
            array('code' => 'TW','country_us' => 'Taiwan','country_fr' => 'Taïwan'),
            array('code' => 'TZ','country_us' => 'Tanzania','country_fr' => 'Tanzanie'),
            array('code' => 'UA','country_us' => 'Ukraine','country_fr' => 'Ukraine'),
            array('code' => 'UG','country_us' => 'Uganda','country_fr' => 'Ouganda'),
            array('code' => 'UM','country_us' => 'U.S. Outlying Islands','country_fr' => 'Îles mineures éloignées des États-Unis'),
            array('code' => 'US','country_us' => 'United States','country_fr' => 'États-Unis'),
            array('code' => 'UY','country_us' => 'Uruguay','country_fr' => 'Uruguay'),
            array('code' => 'UZ','country_us' => 'Uzbekistan','country_fr' => 'Ouzbékistan'),
            array('code' => 'VA','country_us' => 'Vatican City','country_fr' => 'État de la Cité du Vatican'),
            array('code' => 'VC','country_us' => 'St. Vincent & Grenadines','country_fr' => 'Saint-Vincent-et-les-Grenadines'),
            array('code' => 'VE','country_us' => 'Venezuela','country_fr' => 'Venezuela'),
            array('code' => 'VG','country_us' => 'British Virgin Islands','country_fr' => 'Îles Vierges britanniques'),
            array('code' => 'VI','country_us' => 'U.S. Virgin Islands','country_fr' => 'Îles Vierges des États-Unis'),
            array('code' => 'VN','country_us' => 'Vietnam','country_fr' => 'Vietnam'),
            array('code' => 'VU','country_us' => 'Vanuatu','country_fr' => 'Vanuatu'),
            array('code' => 'WF','country_us' => 'Wallis & Futuna','country_fr' => 'Wallis-et-Futuna'),
            array('code' => 'WS','country_us' => 'Samoa','country_fr' => 'Samoa'),
            array('code' => 'XA','country_us' => 'Pseudo-Accents','country_fr' => 'pseudo-accents'),
            array('code' => 'XB','country_us' => 'Pseudo-Bidi','country_fr' => 'pseudo-bidi'),
            array('code' => 'XK','country_us' => 'Kosovo','country_fr' => 'Kosovo'),
            array('code' => 'YE','country_us' => 'Yemen','country_fr' => 'Yémen'),
            array('code' => 'YT','country_us' => 'Mayotte','country_fr' => 'Mayotte'),
            array('code' => 'ZA','country_us' => 'South Africa','country_fr' => 'Afrique du Sud'),
            array('code' => 'ZM','country_us' => 'Zambia','country_fr' => 'Zambie'),
            array('code' => 'ZW','country_us' => 'Zimbabwe','country_fr' => 'Zimbabwe')
          );

          DB::table('countries')->insert($contryArray);
    }
}
