build:
  environment:
    php:
        version: '7.4.1'
  nodes:
    GaelO:
      root_path: './src'
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
      - "./src/data/install/"
  dependency_paths:
      - "./src/vendor/"