build:
  environment:
    php:
        version: '7.4.4'
  nodes:
    GaelO:
      root_path: './GaelO2/GaelO2'
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
      - "./GaelO2/GaelO2/public"
      - "./GaelO2/GaelO2/resources"
  dependency_paths:
      - "./GaelO2/GaelO2/vendor/"