version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]
services:
    gaelo:
        build: gaelo
        restart: unless-stopped
        ports: ["8080:80"]
        #volumes: ["gaelo:/gaelo:Z"]
    orthancexposed:
        build: orthancexposed
        restart: unless-stopped
        ports: ["127.0.0.1:8043:8042"]
        volumes: ["storageexposed:/var/lib/orthanc/db:Z"]
        environment:
            AC_REGISTERED_USERS: "{\"internal\":\"GaelO\",\"external\":\"GaelO\"}"
            TRANSFERS_BUNDLE_DEFAULTS: "true"
            NAME: OrthancExposed
            AC_AUTHENTICATION_ENABLED : "true"
            PEERS: |
                {
                    "OrthancPacs": ["http://orthancpacs:8042/", "GaelO", "GaelO"]
                }
    orthancpacs:
        build: orthancpacs
        depends_on: [index]
        restart: unless-stopped
        ports: ["127.0.0.1:8042:8042"]
        volumes: ["storagepacs:/var/lib/orthanc/db:Z"]
        environment:
            AC_REGISTERED_USERS: "{\"GaelO\":\"GaelO\",\"dicomWeb\":\"dicomWeb\"}"
            DW_ENABLED: "true"
            TRANSFERS_BUNDLE_DEFAULTS: "true"
            AC_AUTHENTICATION_ENABLED : "true"
            NAME: OrthancPacs 
            MYSQL_HOST: index
            MYSQL_USER: orthancPacs
            MYSQL_DB: orthancPacs
            MYSQL_PASSWORD: sassa
    index:
            image: mysql:8.0
            command: [mysqld, --default-authentication-plugin=mysql_native_password, --log-bin-trust-function-creators=1]
            volumes: ["index:/var/lib/mysql:Z"]
            environment:
                    MYSQL_ENABLED: "true" 
                    MYSQL_PASSWORD: sassa
                    MYSQL_USER: orthancPacs
                    MYSQL_DATABASE: orthancPacs
                    MYSQL_ROOT_PASSWORD: foo-root
            restart: unless-stopped
    indexgaelo:
        image: mysql:8.0
        command: [mysqld, --default-authentication-plugin=mysql_native_password, --log-bin-trust-function-creators=1]
        volumes: ["indexgaelo:/var/lib/mysql:Z"]
        environment:
                MYSQL_ENABLED: "true" 
                MYSQL_PASSWORD: gaelo
                MYSQL_USER: gaelo
                MYSQL_DATABASE: gaelo
                MYSQL_ROOT_PASSWORD: gaelo
        restart: unless-stopped
    phpmyadmin:
        depends_on:
        - indexgaelo
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - '8081:80'
        environment:
            PMA_HOST: indexgaelo
            MYSQL_ROOT_PASSWORD: gaelo   

volumes:
        storageexposed:
        storagepacs:
        index:
        #gaelo:
        indexgaelo:
