openapi: "3.0.0"
info:
  title: API Title
  version: '1.0'
paths:
  /api/centers:
    get:
      description: Get centers
      parameters:
        - in: path
          name: code
          required: false
          schema:
            type: integer
          description: Code of the center to get
      responses:
        '200':
          description: OK

    post:
      description: Center creation
      requestBody:
        description: Center details
        required: true
        content:
          application/json:
            schema:
              title: Center
              type: object
              properties:
                code:
                  type: integer
                  description: center code
                name:
                  type: string
                  description: center name
                country_code:
                  type: string
                  description: country code
      responses:
        '200':
          description: OK


  /api/countries:
    get:
      description: Get countries
      parameters:
        - in: path
          name: code
          required: false
          schema:
            type: string
          description: Code of the country to get
      responses:
        '200':
          description: OK

  /api/users/{id}:
    get:
      description: Get user details
      parameters:
        - in: path
          name: id
          required: false
          schema:
            type: integer
          description: Numeric ID of the user to get
      responses:
        '200':
          description: OK

    delete:
      description: Delete user
      parameters:
        - in: path
          name: id
      responses:
        '200':
          description: OK


  /api/users/:
    post:
      description: User creation
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              title: User
              type: object
              properties:
                username:
                  type: string
                  description: username
                lastname:
                  type: string
                  description: last name
                firstname:
                  type: string
                  description: first name
                email:
                  type: string
                  description: email
                phone:
                  type: string
                  description: phone number
                administrator:
                  type: boolean
                  description: is administrator
                center_code:
                  type: integer
                  description: center code
                job:
                  type: string
                  default: CRA
                  description: job (CRA, Monitor, Nuclearist, PI, Radiologist, Study nurse, Supervision)
                orthanc_address:
                  type: string
                  description: orthanc address
                orthanc_login:
                  type: string
                  description: orthanc login
                orthanc_password:
                  type: string
                  description: orthanc password


      responses:
        '201':
          description: User created

    patch:
      description: User password change
      requestBody:
        description: Username and password
        required: true
        content:
          application/json:
            schema:
              title: User
              type: object
              properties:
                id:
                  type: string
                  description: user id
                previous_password:
                  type: string
                  description: previous password
                password1:
                  type: string
                  description: password
                password2:
                  type: string
                  description: password verification
      responses:
        '200':
          description: OK

    get:
      description: Get all users
      responses:
        '200':
          description: OK




