name: 'PHP-Stan'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: 'PHP Stan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build checkout'
        uses: actions/checkout@v4

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: 'Copy .env'
        working-directory: ./GaelO2
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: 'Install Dependencies'
        working-directory: ./GaelO2
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: 'Generate key'
        working-directory: ./GaelO2
        run: php artisan key:generate

      - name: 'Execute PHP Stan'
        working-directory: ./GaelO2
        run: vendor/bin/phpstan analyse app/
permissions:
  contents: read
  packages: write