name: 'PHP-Stan Static Analysis'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: 'PHP Stan Analysis'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build checkout'
        uses: actions/checkout@v3

      - name: 'Copy .env'
        working-directory: ./GaelO2
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - uses: php-actions/composer@v6
        with:
         command: composer install --working-dir GaelO2

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
            path: GaelO2/app/
            php_version : 8.1