name: 'publish'

on:
  push:
    branches:
      - GaelO2
      - GaelO2-dev
    tags:
      - '*'

jobs:
  build:
    name: 'Build and publish'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build checkout'
        uses: actions/checkout@v3
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pixilib/gaelo
          tags: |
            type=ref,event=tag
            v2-latest
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to github registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 'salimkanoun'
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
